seo: 
  site_name: OnememoryDesign.
  title: OnememoryDesign.
  description: Find your Agency for Web-Development and Web-Design here. Get a new website that is fast, reliable and secure.
  keywords: Web-Development, WebDev, Web-Design, New Website
  social_image: /images/favicon.png
  author: Jenny and Patrick 
  favicon_image: /images/favicon.png
social:
  instagram_username: https://www.instagram.com/onememory.design/
  facebook_url: https://www.facebook.com/profile.php?id=61572833130208