seo: 
  site_name: OnememoryDesign
  title: OnememoryDesign
  description: 
  keywords: Web-Development, WebDev, Web-Design
  social_image: 
  author: 
  favicon_image: 
social:
  instagram_username:
  facebook_url: