seo: 
  site_name: OnememoryDesign
  title: OnememoryDesign
  description: 
  keywords: Web-Development, WebDev
  social_image: 
  author: 
  favicon_image: /images/favicon.png
social:
  instagram_username:
  facebook_url:
  twitter_username: 